// Generated by https://quicktype.io

class PopularMoviesModel {
  PopularMoviesModel({
    this.backdropPath,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.title,
    this.voteAverage,
  });

  String? backdropPath;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? title;
  double? voteAverage;

  factory PopularMoviesModel.fromMap(Map<String, dynamic> map) {
    return PopularMoviesModel(
      backdropPath: map['backdrop_path'] ?? "",
      id: map['id'],
      originalLanguage: map['original_language'],
      originalTitle: map['original_title'],
      overview: map['overview'],
      popularity: map['popularity'],
      posterPath: map['poster_path'] ?? "",
      title: map['title'],
      voteAverage: map['vote_average'] is String
          ? double.parse(map['vote_average'])
          : map['vote_average'] is int ? map['vote_average'].toDouble() : map['vote_average'],
    );
  }

  Map<String, dynamic> toMap(){
    return {
      'backdrop_path': backdropPath,
      'id': id,
      'original_language': originalLanguage,
      'original_title': originalTitle,
      'overview': overview,
      'popularity': popularity,
      'poster_path': posterPath,
      'title': title,
      'vote_average': voteAverage,
  };
}
}